baseURL = "http://eosurf.com/"
languageCode = "en-us"
title = "EOSurf"
theme = "landing-page-hugo"
publishDir = "docs"

canonifyUrls = "true"

[params]
    description = "Surf a wave. Hike a mountain. Build on EOS"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "Join our Telegram"
    icon = "telegram"
    url = "https://t.me/eosbeach"

